[project]
name = "deep-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "openai>=1.100.2",
    "pydantic-ai>=0.7.4",
]

[dependency-groups]
dev = [
    "ruff>=0.12.10",
]
